//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopQuanAo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-N1FFA5P\\SQLEXPRESS;Initial Catalog=QL_SHOPQUANAO;Integrated S" +
            "ecurity=True")]
        public string QL_SHOPQUANAOConnectionString {
            get {
                return ((string)(this["QL_SHOPQUANAOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-FSNILVG\\SQLEXPRESS;Initial Catalog=QL_SHOPQUANAO;Integrated S" +
            "ecurity=True")]
        public string QL_SHOPQUANAOConnectionString1 {
            get {
                return ((string)(this["QL_SHOPQUANAOConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-6PUB4VAQN1G\\SQLEXPRESS;Initial Catalog=QL_SHOPQUANAO;Integrated S" +
            "ecurity=True")]
        public string QL_SHOPQUANAOConnectionString2 {
            get {
                return ((string)(this["QL_SHOPQUANAOConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-6PUB4VAQN1G\\SQLEXPRESS;Initial Catalog=QUANLYSHOPQUANAO;Integrate" +
            "d Security=True")]
        public string QUANLYSHOPQUANAOConnectionString {
            get {
                return ((string)(this["QUANLYSHOPQUANAOConnectionString"]));
            }
        }
    }
}
